version: "3.8"

services:
  server:
    build: .
    container_name: bia-server
    ports:
      - "80:8080"
    environment:
      DB_HOST: bia.ce3suii0qq9u.us-east-1.rds.amazonaws.com
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PWD: uqu4C6VhK4LOpDv3m5e7
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /bia/app
        awslogs-stream: bia-server
